In [1]:
import importlib
import pip
import pandas as pd
import numpy as np

In [2]:
def check_and_install_library(library_name):
    try:
        importlib.import_module(library_name)
        print(f"{library_name} has already been installed")
    except ImportError:
        try:
            print(f"{library_name} is being installed...")
            pip.main(['install',library_name])
        except:
            print(f"Please install {library_name} manually")

In [4]:
check_and_install_library('geopy')

geopy is being installed...

WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.

Collecting geopy

  Downloading geopy-2.4.1-py3-none-any.whl (125 kB)

Output()

Collecting geographiclib<3,>=1.52

  Downloading geographiclib-2.0-py3-none-any.whl (40 kB)

Output()

Installing collected packages: geographiclib, geopy

Successfully installed geographiclib-2.0 geopy-2.4.1

[notice] A new release of pip available: 22.3.1 -> 24.2
[notice] To update, run: C:\Users\Administrator\AppData\Local\Programs\Python\Python311\python.exe -m pip install --upgrade pip

In [3]:
from geopy.geocoders import Nominatim

In [4]:
nom = Nominatim(user_agent = 'pasara')

In [5]:
location = nom.geocode('Tema, Ghana')
print(location.latitude)

5.6596441

In [6]:
print(location.longitude)

-0.0096592

In [7]:
def get_lat_long(address):
    address = address + ", Ghana"
    location = nom.geocode(address)
    if location:
        return (location.latitude, location.longitude)
    else:
        return None

In [8]:
user_coordinates = get_lat_long('Tema Community 25')
rest_coordinates = get_lat_long('Tema Community 4')
print(rest_coordinates)

(5.6629295, -0.0104016)

In [9]:
from geopy.distance import geodesic

In [10]:
def calculate_distance(user_coordinates, restaurant_coordinates):
    return geodesic(user_coordinates, restaurant_coordinates).km

In [11]:
distance = calculate_distance(user_coordinates,rest_coordinates)
print(distance)

7.314134491297522

In [12]:
df = pd.read_excel('restaurant_data.xlsx')
df.head()

,Restaurant Name,Avg Rating,Rating Count,Avg Price,Delivery Time,Location
0,Sub Box(The Sandwich & Grill Shop),4.6,10290,GH₵6.00,30–35 min,Cantonment
1,80/20 Burgers and Fries,4.5,92750,GH₵6.00,15–20 min,Cantonment
2,Pinkberry Labone,4.7,17807,GH₵7.00,15–20 min,Cantonment
3,Vida E Café Labone,4.5,27343,GH₵7.00,20–25 min,Cantonment
4,Rocomamas - Labone,4.4,60117,GH₵7.00,20–25 min,Cantonment

In [13]:
df['Avg Price'] = df['Avg Price'].apply(lambda x: x[3:])

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1128 entries, 0 to 1127
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Restaurant Name  1128 non-null   object
 1   Avg Rating       1128 non-null   float64
 2   Rating Count     1128 non-null   int64
 3   Avg Price        1128 non-null   object
 4   Delivery Time    1127 non-null   object
 5   Location         1128 non-null   object
dtypes: float64(1), int64(1), object(4)
memory usage: 53.0+ KB

In [15]:
df['Avg Price'] = df['Avg Price'].apply(lambda x:float(x))

In [16]:
df['Upper'] = df['Delivery Time'].str.split('–').str[1].str.rstrip(' min')

In [17]:
df[df['Avg Rating'] == 0]

,Restaurant Name,Avg Rating,Rating Count,Avg Price,Delivery Time,Location,Upper
28,MaSean UK Mini-Mart,0.0,50065,11.0,40–45 min,Cantonment,45
29,The Shop Accra Eatry,0.0,112120,12.0,30–35 min,Cantonment,35
39,Telefonika - Labone Shop,0.0,76064,8.0,15–20 min,Cantonment,20
44,MaSean UK Mini-Mart,0.0,50065,11.0,40–45 min,Cantonment,45
54,Capitol Cafe and Restaurant,0.0,114641,6.0,35–40 min,Cantonment,40
...,...,...,...,...,...,...,...
1083,Aide Chemists Limited (Pharmacy) - Ogbodjo,0.0,107504,15.0,30–35 min,Lakeside,35
1084,Freshly Frozen Cold Store - Adenta,0.0,101229,18.0,30–35 min,Lakeside,35
1085,Five Two Pharma - Mutti Pharmacy,0.0,112129,11.0,25–30 min,Lakeside,30
1123,1Don Restaurant,0.0,114896,15.0,40–45 min,Lakeside,45
1127,Aide Chemists Limited (Pharmacy) - Ogbodjo,0.0,107504,15.0,30–35 min,Lakeside,35

In [18]:
df.head(50)

,Restaurant Name,Avg Rating,Rating Count,Avg Price,Delivery Time,Location,Upper
0,Sub Box(The Sandwich & Grill Shop),4.6,10290,6.0,30–35 min,Cantonment,35
1,80/20 Burgers and Fries,4.5,92750,6.0,15–20 min,Cantonment,20
2,Pinkberry Labone,4.7,17807,7.0,15–20 min,Cantonment,20
3,Vida E Café Labone,4.5,27343,7.0,20–25 min,Cantonment,25
4,Rocomamas - Labone,4.4,60117,7.0,20–25 min,Cantonment,25
5,Ocean Basket,4.1,66801,7.0,25–30 min,Cantonment,30
6,Pinocchio & La Piazza Osu,4.6,8555,8.0,25–30 min,Cantonment,30
7,Pizzaman Chickenman - La,4.5,77502,8.0,30–35 min,Cantonment,35
8,Papa's Pizza Osu,4.5,7048,9.0,45–50 min,Cantonment,50
9,Cheezzy Pizza Osu,4.5,7060,9.0,30–35 min,Cantonment,35
10,KFC Osu,4.7,9587,10.0,20–25 min,Cantonment,25
11,KFC 37 Liberation,4.5,9625,10.0,25–30 min,Cantonment,30
12,Rocomamas - Labone,4.4,60117,7.0,20–25 min,Cantonment,25
13,Ocean Basket,4.1,66801,7.0,25–30 min,Cantonment,30
14,Wok Boyz - Osu,4.6,60366,8.0,25–30 min,Cantonment,30
15,Wafflemania - Osu,4.5,66070,9.0,40–45 min,Cantonment,45
16,DeliBeli Restaurant & Bar,4.0,15875,9.0,40–45 min,Cantonment,45
17,Lytanan Chez Christine - Osu,3.9,23839,9.0,25–30 min,Cantonment,30
18,KFC Osu,4.7,9587,10.0,20–25 min,Cantonment,25
19,Pizza Inn 37,4.4,7644,10.0,30–35 min,Cantonment,35
20,Yes Chef Super Store,4.4,6608,10.0,30–35 min,Cantonment,35
21,Firefries and Chicken,4.3,32803,10.0,35–40 min,Cantonment,40
22,Marwako Fast Food Labadi,4.5,30400,12.0,30–35 min,Cantonment,35
23,Starbites Express Stadium,4.4,46367,12.0,25–30 min,Cantonment,30
24,Glovers Pizza,4.5,94445,10.0,55–60 min,Cantonment,60
25,Bistrohot,4.2,86008,12.0,55–60 min,Cantonment,60
26,Hunga Killa,4.1,70406,12.0,30–35 min,Cantonment,35
27,Zeallers Restaurant,4.1,8693,12.0,40–45 min,Cantonment,45
28,MaSean UK Mini-Mart,0.0,50065,11.0,40–45 min,Cantonment,45
29,The Shop Accra Eatry,0.0,112120,12.0,30–35 min,Cantonment,35
30,SNEDA Shopping Centre Limited - Osu,4.8,75550,9.0,20–25 min,Cantonment,25
31,Telefonika - Osu Shop,4.8,76065,10.0,20–25 min,Cantonment,25
32,Kwikmart,4.8,105255,18.0,25–30 min,Cantonment,30
33,Kwikmart Dzorwulu,4.8,77387,21.0,35–40 min,Cantonment,40
34,Fair Way Minimarket Labone,4.7,82423,6.0,20–25 min,Cantonment,25
35,Fair Way Minimarket East Legon,4.7,82426,23.0,60–65 min,Cantonment,65
36,Lincare Pharmacy,4.7,102820,29.0,35–40 min,Cantonment,40
37,SNEDA Shopping Centre Limited - Spintex,4.6,75541,20.0,35–40 min,Cantonment,40
38,Fair Way Minimarket Spintex,4.5,82424,24.0,55–60 min,Cantonment,60
39,Telefonika - Labone Shop,0.0,76064,8.0,15–20 min,Cantonment,20
40,Palace Mall Spintex,4.3,76877,18.0,45–50 min,Cantonment,50
41,Lytanan Chez Christine - Osu,3.9,23839,9.0,25–30 min,Cantonment,30
42,Firefries and Chicken,4.3,32803,10.0,35–40 min,Cantonment,40
43,Glovers Pizza,4.5,94445,10.0,55–60 min,Cantonment,60
44,MaSean UK Mini-Mart,0.0,50065,11.0,40–45 min,Cantonment,45
45,Zeallers Restaurant,4.1,8693,12.0,40–45 min,Cantonment,45
46,Bistrohot,4.2,86008,12.0,55–60 min,Cantonment,60
47,Meirrys Special Food and Drinks,4.7,70245,13.0,50–55 min,Cantonment,55
48,Master Hand Chinese Restaurant,3.6,30927,14.0,45–50 min,Cantonment,50
49,Lima’s Tasty Bite,4.4,108920,14.0,35–40 min,Cantonment,40

In [49]:
# def rating_impute(rating_count):
#     if rating_count > 110000:
#         upp_avg
#     elif 100000 < rating_count <= 110000:
#         avg
#     elif rating_count < 100000:
#         bel_avg


# avg = df['Avg Rating'].mean()
# upp_avg = avg + 0.5
# bel_avg = avg - 0.5

In [19]:
from sklearn.impute import SimpleImputer

In [20]:
df['Avg Rating'] = df['Avg Rating'].apply(lambda x: np.nan if x == 0 else x)
avg_rating_array = df['Avg Rating'].to_numpy().reshape(-1, 1)

imputer = SimpleImputer(strategy='mean')

imputer.fit(avg_rating_array)

imputed_ratings = imputer.transform(avg_rating_array)

df['Avg Rating'] = imputed_ratings.squeeze()

In [21]:
df.head()

,Restaurant Name,Avg Rating,Rating Count,Avg Price,Delivery Time,Location,Upper
0,Sub Box(The Sandwich & Grill Shop),4.6,10290,6.0,30–35 min,Cantonment,35
1,80/20 Burgers and Fries,4.5,92750,6.0,15–20 min,Cantonment,20
2,Pinkberry Labone,4.7,17807,7.0,15–20 min,Cantonment,20
3,Vida E Café Labone,4.5,27343,7.0,20–25 min,Cantonment,25
4,Rocomamas - Labone,4.4,60117,7.0,20–25 min,Cantonment,25

In [22]:
cn = df[df['Location'] == 'Cantonment' ]
cn.head(55)

,Restaurant Name,Avg Rating,Rating Count,Avg Price,Delivery Time,Location,Upper
0,Sub Box(The Sandwich & Grill Shop),4.600000,10290,6.0,30–35 min,Cantonment,35
1,80/20 Burgers and Fries,4.500000,92750,6.0,15–20 min,Cantonment,20
2,Pinkberry Labone,4.700000,17807,7.0,15–20 min,Cantonment,20
3,Vida E Café Labone,4.500000,27343,7.0,20–25 min,Cantonment,25
4,Rocomamas - Labone,4.400000,60117,7.0,20–25 min,Cantonment,25
5,Ocean Basket,4.100000,66801,7.0,25–30 min,Cantonment,30
6,Pinocchio & La Piazza Osu,4.600000,8555,8.0,25–30 min,Cantonment,30
7,Pizzaman Chickenman - La,4.500000,77502,8.0,30–35 min,Cantonment,35
8,Papa's Pizza Osu,4.500000,7048,9.0,45–50 min,Cantonment,50
9,Cheezzy Pizza Osu,4.500000,7060,9.0,30–35 min,Cantonment,35
10,KFC Osu,4.700000,9587,10.0,20–25 min,Cantonment,25
11,KFC 37 Liberation,4.500000,9625,10.0,25–30 min,Cantonment,30
12,Rocomamas - Labone,4.400000,60117,7.0,20–25 min,Cantonment,25
13,Ocean Basket,4.100000,66801,7.0,25–30 min,Cantonment,30
14,Wok Boyz - Osu,4.600000,60366,8.0,25–30 min,Cantonment,30
15,Wafflemania - Osu,4.500000,66070,9.0,40–45 min,Cantonment,45
16,DeliBeli Restaurant & Bar,4.000000,15875,9.0,40–45 min,Cantonment,45
17,Lytanan Chez Christine - Osu,3.900000,23839,9.0,25–30 min,Cantonment,30
18,KFC Osu,4.700000,9587,10.0,20–25 min,Cantonment,25
19,Pizza Inn 37,4.400000,7644,10.0,30–35 min,Cantonment,35
20,Yes Chef Super Store,4.400000,6608,10.0,30–35 min,Cantonment,35
21,Firefries and Chicken,4.300000,32803,10.0,35–40 min,Cantonment,40
22,Marwako Fast Food Labadi,4.500000,30400,12.0,30–35 min,Cantonment,35
23,Starbites Express Stadium,4.400000,46367,12.0,25–30 min,Cantonment,30
24,Glovers Pizza,4.500000,94445,10.0,55–60 min,Cantonment,60
25,Bistrohot,4.200000,86008,12.0,55–60 min,Cantonment,60
26,Hunga Killa,4.100000,70406,12.0,30–35 min,Cantonment,35
27,Zeallers Restaurant,4.100000,8693,12.0,40–45 min,Cantonment,45
28,MaSean UK Mini-Mart,4.302197,50065,11.0,40–45 min,Cantonment,45
29,The Shop Accra Eatry,4.302197,112120,12.0,30–35 min,Cantonment,35
30,SNEDA Shopping Centre Limited - Osu,4.800000,75550,9.0,20–25 min,Cantonment,25
31,Telefonika - Osu Shop,4.800000,76065,10.0,20–25 min,Cantonment,25
32,Kwikmart,4.800000,105255,18.0,25–30 min,Cantonment,30
33,Kwikmart Dzorwulu,4.800000,77387,21.0,35–40 min,Cantonment,40
34,Fair Way Minimarket Labone,4.700000,82423,6.0,20–25 min,Cantonment,25
35,Fair Way Minimarket East Legon,4.700000,82426,23.0,60–65 min,Cantonment,65
36,Lincare Pharmacy,4.700000,102820,29.0,35–40 min,Cantonment,40
37,SNEDA Shopping Centre Limited - Spintex,4.600000,75541,20.0,35–40 min,Cantonment,40
38,Fair Way Minimarket Spintex,4.500000,82424,24.0,55–60 min,Cantonment,60
39,Telefonika - Labone Shop,4.302197,76064,8.0,15–20 min,Cantonment,20
40,Palace Mall Spintex,4.300000,76877,18.0,45–50 min,Cantonment,50
41,Lytanan Chez Christine - Osu,3.900000,23839,9.0,25–30 min,Cantonment,30
42,Firefries and Chicken,4.300000,32803,10.0,35–40 min,Cantonment,40
43,Glovers Pizza,4.500000,94445,10.0,55–60 min,Cantonment,60
44,MaSean UK Mini-Mart,4.302197,50065,11.0,40–45 min,Cantonment,45
45,Zeallers Restaurant,4.100000,8693,12.0,40–45 min,Cantonment,45
46,Bistrohot,4.200000,86008,12.0,55–60 min,Cantonment,60
47,Meirrys Special Food and Drinks,4.700000,70245,13.0,50–55 min,Cantonment,55
48,Master Hand Chinese Restaurant,3.600000,30927,14.0,45–50 min,Cantonment,50
49,Lima’s Tasty Bite,4.400000,108920,14.0,35–40 min,Cantonment,40
50,MGT Delicacies,4.300000,94770,15.0,35–40 min,Cantonment,40
51,Yum Yum - Airport,4.100000,99289,16.0,35–40 min,Cantonment,40
52,Delicious Kitchen,4.300000,53752,17.0,55–60 min,Cantonment,60
53,Golden Relish Catering,4.400000,63234,6.0,20–25 min,Cantonment,25
54,Capitol Cafe and Restaurant,4.302197,114641,6.0,35–40 min,Cantonment,40

In [23]:
df[pd.isnull(df['Upper'])]

,Restaurant Name,Avg Rating,Rating Count,Avg Price,Delivery Time,Location,Upper
908,11:11 Nigerian Kitchen,4.1,78988,12.0,NaN,"Accra,Circle",NaN

In [24]:
df = df[df['Restaurant Name'] != 'Nigerian Kitchen']

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1128 entries, 0 to 1127
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Restaurant Name  1128 non-null   object
 1   Avg Rating       1128 non-null   float64
 2   Rating Count     1128 non-null   int64
 3   Avg Price        1128 non-null   float64
 4   Delivery Time    1127 non-null   object
 5   Location         1128 non-null   object
 6   Upper            1127 non-null   object
dtypes: float64(2), int64(1), object(4)
memory usage: 61.8+ KB

In [26]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import StandardScaler

# Selecting relevant features
content_features = df[['Avg Rating', 'Avg Price', 'Upper']].copy()

content_features.dropna(inplace=True)

scaler = StandardScaler()
content_features_scaled = scaler.fit_transform(content_features)

similarity_matrix = cosine_similarity(content_features_scaled)


def recommend_similar_restaurants(restaurant_name, top_n=5):
    # Get index of the input restaurant
    idx = df[df['Restaurant Name'] == restaurant_name].index[0]
    
    # Get similarity scores for the restaurant
    similarity_scores = list(enumerate(similarity_matrix[idx]))
    
    # Sort restaurants based on similarity scores
    similarity_scores = sorted(similarity_scores, key=lambda x: x[1], reverse=True)
    
    # Get the top_n most similar restaurants
    top_similar_restaurants = similarity_scores[1:top_n+1]
    
    # Return the restaurant names
    similar_restaurants = [df.iloc[i[0]]['Restaurant Name'] for i in top_similar_restaurants]
    return similar_restaurants

In [27]:
similar_restaurants = recommend_similar_restaurants('Sub Box(The Sandwich & Grill Shop)')
print(similar_restaurants)

['Sub Box(The Sandwich & Grill Shop)', 'Waakye Madina', 'Pizzaman Chickenman - La', 'Mawusinu Foods - TF Legon', 'Pizzaman Chickenman - Mataheko']

In [28]:
df['Coordinates'] = df['Location'].apply(get_lat_long)

In [29]:
def filter_by_location(user_lat, user_lon, max_distance_km=12):
    user_coords = (user_lat, user_lon)
    
    
    df['Distance_km'] = df['Coordinates'].apply(lambda x: geodesic(user_coords, x).km)
    
    nearby_restaurants = df[df['Distance_km'] <= max_distance_km]

    return nearby_restaurants

### Two versions of the recommender system
##### - The first one requires an input restaurant to be able to fetch similar restaurants
##### - The second one just recommends restaurants for a user based on proximity,rating and popularity

In [33]:
def pasara_recommender1(user_lat, user_lon, restaurant_name, max_distance_km=12, top_n=10):
    nearby_restaurants = filter_by_location(user_lat, user_lon, max_distance_km)
    
    if nearby_restaurants.empty:
        return "No nearby restaurants found."
    
    nearby_indices = nearby_restaurants.index
    
    try:
        input_idx =df[df['Restaurant Name'] == restaurant_name].index[0]
    except IndexError:
        return "Restaurant not found."
    
    similarity_scores = list(enumerate(similarity_matrix[input_idx]))
    
    # Filter similarity scores to only include nearby restaurants
    similarity_scores = [(i, score) for i, score in similarity_scores if i in nearby_indices]
    
    similarity_scores = sorted(similarity_scores, key=lambda x: x[1], reverse=True)
    
    top_similar_nearby = similarity_scores[1:top_n+1]
    
    recommended_restaurants = [df.iloc[i[0]]['Restaurant Name'] for i in top_similar_nearby]
    
    return recommended_restaurants

In [34]:

recommendations = pasara_recommender1(5.6037, -0.1870, 'Sub Box(The Sandwich & Grill Shop)', 5, 5)
print(recommendations)

['Sub Box(The Sandwich & Grill Shop)', 'Pizzaman Chickenman - La', 'Mawusinu Foods - TF Legon', "Mr Wu's Chinese Food Legon", "Mr Wu's Chinese Food Legon"]

In [37]:
def pasara_recommender2(user_lat, user_lon, max_distance_km=12, top_n=10):
    
    nearby_restaurants = filter_by_location(user_lat, user_lon, max_distance_km)
    
    if nearby_restaurants.empty:
        return "No nearby restaurants found."
    

    nearby_restaurants = nearby_restaurants.sort_values(by=['Rating Count','Avg Rating'], ascending=[False, False])
    

    top_recommended = nearby_restaurants.head(top_n)
    
    recommended_restaurants = top_recommended['Restaurant Name'].tolist()
    
    return recommended_restaurants

In [38]:
recommendations = pasara_recommender2(5.6037, -0.1870, 5, 5)
print(recommendations)

['Capitol Cafe and Restaurant', "Shelly's Bistro and Bar", 'The Shop Accra Eatry', 'Normm’s Restaurant & Lounge', 'Lima’s Tasty Bite']

In [43]:
test = nom.geocode('Cantonment,Ghana')

In [45]:
co = test.latitude, test.longitude

In [47]:
user = (5.6037, -0.1870)

In [49]:
geodesic(co,user).km

3.3913556513748766